all: true
dir: '{{.InterfaceDir}}'
filename: 'mock_{{.InterfaceName | snakecase}}.go'
structname: Mock{{.InterfaceName}}
pkgname: '{{.SrcPackageName}}'
inpackage: true
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/hyperscale-stack/security:
    config:
      recursive: true
