// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package token

import mock "github.com/stretchr/testify/mock"

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator struct {
	mock.Mock
}

// GenerateAccessToken provides a mock function with given fields: generateRefresh
func (_m *MockGenerator) GenerateAccessToken(generateRefresh bool) (string, string, error) {
	ret := _m.Called(generateRefresh)

	var r0 string
	if rf, ok := ret.Get(0).(func(bool) string); ok {
		r0 = rf(generateRefresh)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(bool) string); ok {
		r1 = rf(generateRefresh)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(bool) error); ok {
		r2 = rf(generateRefresh)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
