// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package oauth2

import mock "github.com/stretchr/testify/mock"

// MockAccessProvider is an autogenerated mock type for the AccessProvider type
type MockAccessProvider struct {
	mock.Mock
}

// LoadAccess provides a mock function with given fields: token
func (_m *MockAccessProvider) LoadAccess(token string) (*AccessData, error) {
	ret := _m.Called(token)

	var r0 *AccessData
	if rf, ok := ret.Get(0).(func(string) *AccessData); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AccessData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveAccess provides a mock function with given fields: token
func (_m *MockAccessProvider) RemoveAccess(token string) error {
	ret := _m.Called(token)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveAccess provides a mock function with given fields: _a0
func (_m *MockAccessProvider) SaveAccess(_a0 *AccessData) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*AccessData) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
