// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package oauth2

import mock "github.com/stretchr/testify/mock"

// MockClientProvider is an autogenerated mock type for the ClientProvider type
type MockClientProvider struct {
	mock.Mock
}

// LoadClient provides a mock function with given fields: id
func (_m *MockClientProvider) LoadClient(id string) (Client, error) {
	ret := _m.Called(id)

	var r0 Client
	if rf, ok := ret.Get(0).(func(string) Client); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveClient provides a mock function with given fields: id
func (_m *MockClientProvider) RemoveClient(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveClient provides a mock function with given fields: _a0
func (_m *MockClientProvider) SaveClient(_a0 Client) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(Client) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
