// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package oauth2

import mock "github.com/stretchr/testify/mock"

// MockRefreshProvider is an autogenerated mock type for the RefreshProvider type
type MockRefreshProvider struct {
	mock.Mock
}

// LoadRefresh provides a mock function with given fields: token
func (_m *MockRefreshProvider) LoadRefresh(token string) (*AccessInfo, error) {
	ret := _m.Called(token)

	var r0 *AccessInfo
	if rf, ok := ret.Get(0).(func(string) *AccessInfo); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AccessInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveRefresh provides a mock function with given fields: token
func (_m *MockRefreshProvider) RemoveRefresh(token string) error {
	ret := _m.Called(token)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveRefresh provides a mock function with given fields: _a0
func (_m *MockRefreshProvider) SaveRefresh(_a0 *AccessInfo) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*AccessInfo) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
