// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package authentication

import mock "github.com/stretchr/testify/mock"

// MockUserProvider is an autogenerated mock type for the UserProvider type
type MockUserProvider struct {
	mock.Mock
}

// LoadUserByUsername provides a mock function with given fields: username
func (_m *MockUserProvider) LoadUserByUsername(username string) (User, error) {
	ret := _m.Called(username)

	var r0 User
	if rf, ok := ret.Get(0).(func(string) User); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
